[tool.poetry]
name = "pythonlimpador"
version = "0.0.7"
description = ""
authors = ["Luiz <luizfantini_nt@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
pillow = "^11.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
